// Generated by Wrangler
// Runtime types generated with workerd

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface CloudflareBindings extends Cloudflare.Env {
    DB: D1Database;
    STRAVA_CLIENT_ID: string;
    STRAVA_CLIENT_SECRET: string;
    STRAVA_REDIRECT_URI: string;
    JWT_SECRET: string;
}